services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "2009"
    ports:
      "5432:5432"
    volumes:
    - db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - 8888:8888
    environment:
    - 'PGADMIN_DEFAULT_EMAIL=admin@example.com'
    - 'PGADMIN_DEFAULT_PASSWORD=admin'
    - 'PGADMIN_LISTEN_PORT=8888'

volumes:
  db:
    driver:  local